# Generated by Django 3.2 on 2021-07-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('symptom', models.CharField(max_length=999, null=True)),
                ('cause', models.CharField(max_length=999, null=True)),
                ('treat', models.CharField(max_length=999, null=True)),
                ('prevent', models.CharField(max_length=999, null=True)),
                ('advice', models.CharField(max_length=999, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
